{% set name = "sv2v" %}
{% set version = "v0.0.10" %}
{% set tag = "v0.0.10" %}
{% set build_number = environ.get('GIT_DESCRIBE_NUMBER', '0') %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/zachjs/sv2v.git
  git_rev: {{ tag }}

build:
  number: {{ build_number }}
  string: {{ [build_number, ('h' + PKG_HASH), environ.get('GIT_DESCRIBE_HASH', '')]|join('_') }}
  skip: True # [not linux64]

requirements:
  build:
    - stack
    - make
    - python>=3

test:
  commands:
    - sv2v --version

about:
  home: https://github.com/ucb-bar/sv2v-feedstock
  summary: sv2v conda package

extra:
  recipe-maintainers:
    - abejgonzalez
